apiVersion: v1
kind: Service
metadata:
  name: demopython
spec:
  type: LoadBalancer
  selector:
    app: demopython
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080
