apiVersion: v1
kind: Service
metadata:
  name: demo_python
spec:
  type: LoadBalancer
  selector:
    app: demo_python
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080
